#!/bin/bash

if [ "`redis-cli get stage`" == "" ]; then
    echo "[nomadic][cabage][installer] apt updating..."
    sudo apt-get update > /dev/null
    echo "[nomadic][cabage][installer] apt updated."
    echo "[nomadic][cabage][installer] apt upgrading..."
    sudo apt-get upgrade -y > /dev/null
    echo "[nomadic][cabage][installer] apt upgraded."
    echo "[nomadic][cabage][installer] apt packages installing... (you may need to answer configuration questions)"
    sudo apt-get install -qq ruby ruby-dev curl emacs screen mosquitto mosquitto-clients nginx tor aircrack-ng tshark nmap ii sysvbanner termrec termsaver tina wifite netcat vim diceware di redis-server redis-tools inotify-tools build-essential ircd-hybrid tinymux tintin++ slashem
    echo "[nomadic][cabage][installer] apt packages installed."
    echo "[nomadic][cabage][node] blanking random device configuration."
    redis-cli set ID `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1` > /dev/null;
    redis-cli set NICK NONE > /dev/null;
    redis-cli set CITY NONE > /dev/null;
    redis-cli set TEAM NONE > /dev/null;
    redis-cli set GROUP NONE > /dev/null;
    redis-cli set TOK `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 1` > /dev/null;
    redis-cli set PASS `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1` > /dev/null;
    echo "[nomadic][cabage][node] configured."
    # get network config
    echo "[nomadic][cabage][ircd] restarting..."
    sudo service ircd-hybrid restart
    echo "[nomadic][cabage][ircd] restarted."
    # get nginx config
    echo "[nomadic][cabage][httpd] restarting..."
    sudo service nginx restart
    echo "[nomadic][cabage][httpd] restarted."
    echo "[nomadic][cabage][ruby] installing gems..."
    sudo gem install --no-rdoc --no-ri rqrcode redis-objects mqtt pry thin sinatra > /dev/null
    echo "[nomadic][cabage][ruby] installed."
    echo "[nomadic][cabage][irc] configuring..."
    city=`redis-cli get CITY`
    pass=`echo -n $city | shasum | cut -c8-16`
    redis-cli set pass $pass > /dev/null

    echo "(require 'erc-join)(erc-autojoin-mode 1)" > ~/.irc.el
    echo "(setq erc-autojoin-channels-alist " >> ~/.irc.el
    echo "'((\"vango.me\" \"#`redis-cli get CITY`\" \"#`redis-cli get ID`\")))" >> ~/.irc.el
    echo "(erc :server \"vango.me\" :full-name \"`redis-cli get ID`\" :nick \"`redis-cli get ID`\" :password \"$pass\")" >> ~/.irc.el
    echo "[nomadic][cabage][irc] configured."
    echo "[nomadic][cabage][screen] reset configuration."
    echo 'screen -t "#" emacs -nw --load ~/.irc.el index.org' > ~/.screenrc
    echo "[nomadic][cabage][tor] configuring."
    mkdir -p ~/.tor > /dev/null
    echo "HiddenServiceDir /home/pi/.tor" > ~/.torrc
    echo "HiddenServicePort 80 127.0.0.1:8888" >> ~/.torrc
    echo "HiddenServicePort 22 127.0.0.1:22" >> ~/.torrc
    echo "#-#-#-#-#-#-#-#-#-#-#-#-#-#"
    echo "|                         |"
    echo "#      Wait For 100%      #"
    echo "|          then           |"
    echo "#         Ctrl-c          #"
    echo "|                         |"
    echo "#-#-#-#-#-#-#-#-#-#-#-#-#-#"
    chmod 700 ~/.tor
    sudo pkill tor
    tor -f ~/.torrc
    redis-cli set ONION `sudo cat /home/pi/.tor/hostname` > /dev/null
    echo "[nomadic][cabage][tor] configured."
    sudo update-alternatives --config editor
    sudo update-alternatives --config x-terminal-emulator
    sudo update-alternatives --config x-www-browser
    redis-cli set stage 0 > /dev/null
    echo "[nomadic][cabage] READY!"
    exit 0
else
    rm -f lib/*~
    rm -f bin/*~
    rm -f views/*~
    rm -f public/*~
    ruby bin/init.rb
    exit 0
fi
