#!/bin/bash

if [ "`redis-cli get stage`" == "" ]; then
    sudo apt update
    sudo apt upgrade
    sudo apt install -y ruby ruby-dev curl emacs screen mosquitto mosquitto-clients nginx tor aircrack-ng tshark nmap ii wifite netcat vim redis-server redis-tools inotify-tools build-essential ircd-hybrid tinymux tintin++ slashem
    redis-cli set ID `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1`;
    redis-cli set NICK NONE;
    redis-cli set CITY NONE;
    redis-cli set TEAM NONE;
    redis-cli set GROUP NONE;
    redis-cli set TOK `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 1`;
    redis-cli set PASS `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1`;
    # get network config
    sudo service ircd-hybrid restart
    # get nginx config
    sudo service nginx restart
    sudo gem install --no-rdoc --no-ri redis-objects mqtt pry thin sinatra
    city=`redis-cli get CITY`
    pass=`echo -n $city | shasum | cut -c8-16`
    redis-cli set pass $pass

    echo "(require 'erc-join)(erc-autojoin-mode 1)" > ~/.irc.el
    echo "(setq erc-autojoin-channels-alist " >> ~/.irc.el
    echo "'((\"vango.me\" \"#`redis-cli get CITY`\" \"#`redis-cli get ID`\")))" >> ~/.irc.el
    echo "(erc :server \"vango.me\" :full-name \"`redis-cli get ID`\" :nick \"`redis-cli get ID`\" :password \"$pass\")" >> ~/.irc.el
    echo 'screen -t "#" emacs -nw --load ~/.irc.el index.org' >> ~/.screenrc

    redis-cli set stage 0
    echo "#-#-#-#-#-#-#-#-#-#-#-#-#-#"
    wcho "|                         |"
    echo "#         DONE!           #"
    echo "|                         |"
    echo "#-#-#-#-#-#-#-#-#-#-#-#-#-#"
else
    source credentials.sh
    git pull
    rm lib/*~ > /dev/null
    rm bin/*~ > /dev/null
    if [ "$1" != "quiet" ]; then
	redis-cli monitor &
	mosquitto_sub -h localhost -t '#' &
    fi
    ruby bin/init.rb
fi
