#!/bin/bash

export WORK_NMAP='-v -A';

function git_repo_commit_and_push() {
    git add . && git commit -m "$*" && git push;
}               
watch() {
    mkdir -p $1;
    inotifywait -mq \
	      --timefmt '%s' \
	      -e modify,delete \
	      --format '{ "timestamp": "%T", "events": "%e", "file": "%f" }' $1 | while read out;
    do
	redis-cli publish "WATCH.$1" "$out";
    done > /dev/null;
}


if [ "$1" == "ssh" ]; then
    shift;
    ssh $*;
elif [ "$1" == "push" ]; then
    shift;
    git_repo_commit_and_push $*;
elif [ "$1" == "pull" ]; then
    git pull;
elif [ "$1" == "user" ]; then
    export WORK_USER=$2;
elif [ "$1" == "wifi" ]; then
    wicd-curses;
elif [ "$1" == "hack" ]; then
    sudo wifite; 
elif [ "$1" == "browser" ]; then
    x-www-browser https://vango.me &
elif [ "$1" == "shark" ]; then
    shift
    sudo tshark $*;
elif [ "$1" == "fingerprint" ]; then
    shift
    nmap $WORK_NMAP $*;
elif [ "$1" == "scanme" ]; then
    nmap $WORK_NMAP scanme.nmap.org;
elif [ "$1" == "watch" ]; then
    watch $2;
    echo "[nomadic][work][watch] publishing events on WATCH.$2"
elif [ "$1" == "tor" ]; then
    pkill tor && tor -f ~/.torrc > ~/.tor.log &
    echo "[nomadic][tor][http] running."
    echo "[nomadic][tor][ssh] running."
    echo "[nomadic][tor][irc] running."
    echo "[nomadic][tor][log] collecting logs at ~/.tor.log"
elif [ "$1" == "add" ]; then
    redis-cli hset nomadic $2 true > /dev/null
    echo "[nomadic] extension will be installed on next restart."
else
    echo "usage: work [action]";
    echo " ssh <user@domain>";
    echo " push <your commit message>";
    echo " pull";
    echo " browser";
    echo " user <username>";
    echo " browser";
    echo " wifi";
    echo " hack";
    echo " shark";
    echo " fingerprint <domain>";
    echo " scanme";
    echo " watch <dir>";
    echo " tor";
    echo " add <extension>"
    # use carefully.
fi                                                                      

